//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Controlador.cpp
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#include "Controlador.h"

Controlador::Controlador() {}

void Controlador::ProcesarEquipos() {
	string s;
	int m,ms, resp, t;
	float pc;
do{
	s=ve.LeerString("Numero de el serial:");
	t=ve.LeerInt("El tipo de equipo es (1=Computador de escritorio- 2=Laptop)");
	m=ve.LeerInt("La marca de el equipo es(1=HP-2=Toshiba-3=Dell-4=Otros):");
	ms=ve.LeerInt(" El Mes de compra es: (1...12) ");
	pc=ve.LeerFloat("El precio de compra de el equipo es:");
	if(t==1){
		me.SetSerial(s);
		me.SetTipo(t);
		me.SetMarca(m);
		me.SetMes(ms);
		me.SetPrecioC(pc);
		ve.ImprimrirEquipo(me.Det_PrecioV(),me.Det_MontoIva(),me.Det_MontoFact());
		mem.ProcesaEscritorio(me);
   }else{
	   ml.SetSerial(s);
	   ml.SetTipo(t);
	   ml.SetMarca(m);
	   ml.SetMes(ms);
	   ml.SetPrecioC(pc);
	   ve.ImprimrirEquipo(ml.Det_PrecioV(),ml.Det_MontoIva(),ml.Det_MontoFact());
	   mem.ProcesarLaptpo(ml);
  }
		resp=ve.SeleccionarRespuesta("Desea procesar otro equipo(1=Si-2=No)?");
	}while(resp==1);
		vem.ImprimirEmpresa(mem.GetAcum_M(),mem.Det_IncreT(),mem.PorcLaptop(),mem.PorcEscri(),mem.GetAcum_MontoT());
}

