//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Controlador.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_CONTROLADOR_H)
#define _CONTROLADOR_H

#include "MEscritorio.h"
#include "MLaptop.h"
#include "MEmpresa.h"
#include "VEquipo.h"
#include "VEmpresa.h"

class Controlador {
public:
	MEscritorio me;
	MLaptop ml;
	MEmpresa mem;
	VEquipo ve;
	VEmpresa vem;
	Controlador();
	void ProcesarEquipos();
};

#endif  //_CONTROLADOR_H
