//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MEmpresa.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_MEMPRESA_H)
#define _MEMPRESA_H

#include "MEscritorio.h"
#include "MLaptop.h"

class MEmpresa {
private:
	float acum_ma,acum_m,acum_montot;
	int cont_laptop,cont_equipos,cont_escri;
public:
	 MEmpresa();
	void ProcesaEscritorio(MEscritorio me);
	void ProcesarLaptpo(MLaptop ml);
	float GetAcum_Ma();
	float GetAcum_M();
	float GetAcum_MontoT();
	float Det_IncreT();
	float PorcLaptop();
	float PorcEscri();
};

#endif  //_MEMPRESA_H
