//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MEquipo.cpp
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#include "MEquipo.h"

MEquipo::MEquipo(){}


MEquipo::MEquipo(string s, int m, float pc, int me, int t) {
	    serial=s;
		marca=m;
		precioc=pc;
		mes=me;
		tipo=t;
}

void MEquipo::SetSerial(string s) {
	serial=s;
}

void MEquipo::SetMarca(int m) {
	marca=m;
}

void MEquipo::SetPrecioC(float pc) {
	precioc=pc;
}

void MEquipo::SetMes(int me) {
	mes=me;
}
void MEquipo::SetTipo(int t){
	tipo=t;
}
string MEquipo::GetSerial() {
	return serial;
}
int MEquipo::GetMarca() {
	return marca;
}
float MEquipo::GetPrecioC() {
	return precioc;
}
int MEquipo::GetMes() {
	return mes;
}
int MEquipo::GetTipo(){
	return tipo;
}
int MEquipo::Det_Trimestre() {
	if(mes==1 or mes==2 or mes==3)
			return 1;
		else if(mes==4 or mes==5 or mes==6)
			return 2;
		else if(mes==7 or mes==8 or mes==9)
			return 3;
		else if(mes==10 or mes==11 or mes==12)
			return 4;
		else return 0;
}

