//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MEquipo.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_MEQUIPO_H)
#define _MEQUIPO_H
#include <string>

using namespace std;

class MEquipo {
private:
	string serial;
	int marca;
	float precioc;
	int mes;
	int tipo;

public:
    MEquipo();
	MEquipo(string s, int m, float pc, int me, int t);
	void SetSerial(string s);
	void SetMarca(int m);
	void SetPrecioC(float pc);
	void SetMes(int me);
	void SetTipo(int t);
	string GetSerial();
	int GetMarca();
	float GetPrecioC();
	int GetMes();
	int GetTipo();
	int Det_Trimestre();
};

#endif  //_MEQUIPO_H
