//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MEscritorio.cpp
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#include "MEscritorio.h"

MEscritorio::MEscritorio() {}

MEscritorio::MEscritorio(string s, int m, float pc, int me, int t){}

float MEscritorio :: Det_IncreMa(){
			if(GetMarca()==1)
				return GetPrecioC()*0.05;
			else
				return GetPrecioC()*0.08;
			return 0;
}
float MEscritorio::Det_IncreM(){
		if(Det_Trimestre()==2 or Det_Trimestre()==3)
				return GetPrecioC()*0.10;
			else if(Det_Trimestre()==4)
				return GetPrecioC()*0.15;
			else return 0;
}

float MEscritorio::Det_MontoIva() {
	return Det_PrecioV()* 0.12;
}

float MEscritorio::Det_PrecioV() {
	return GetPrecioC() + Det_IncreM() + Det_IncreMa();
}

float MEscritorio::Det_MontoFact() {
	return Det_PrecioV() + Det_MontoIva();
}
