//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MLaptop.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_MLAPTOP_H)
#define _MLAPTOP_H
#include "MEquipo.h"

class MLaptop : public MEquipo {
public:
	MLaptop();
	MLaptop(string s, int m, float pc, int me, int t);
	float Det_IncreMa();
	float Det_IncreM();
	float Det_MontoIva();
	float Det_PrecioV();
	float Det_MontoFact();
};

#endif  //_MLAPTOP_H
