//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VEmpresa.cpp
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#include "VEmpresa.h"

VEmpresa::VEmpresa() {}

void VEmpresa::ImprimirEmpresa(float ic_mes, float inc_tip,float porcl,float porce,float mon_tot) {
	cout<<"Monto de incremento por mes es:"<< ic_mes<<endl;
	cout<<"Incremento por tipo es:"<<inc_tip<<endl;
	cout<<"El porcentaje de laptop es de:"<< porcl<<endl;
	cout<<"El porcentaje de escritorio es de:"<<porce<<endl;
	cout<<"Monto total facturado es:"<<mon_tot<<endl;

}

