//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VEmpresa.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_VEMPRESA_H)
#define _VEMPRESA_H
#include "VGeneral.h"

class VEmpresa : public VGeneral {
public:
	VEmpresa();
	void ImprimirEmpresa(float ic_mes, float inc_tip, float porcl,float porc,float mon_tot);
};

#endif  //_VEMPRESA_H
