//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VEquipo.cpp
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#include "VEquipo.h"

VEquipo::VEquipo() {}

void VEquipo::ImprimrirEquipo(float pv,float mi, float mf) {
	cout<<"El precio venta es:"<<pv<<endl;
	cout<<"El monto iva es :"<<mi<<endl;
	cout<<"El monto facturado es:"<<mf<<endl;
}

