//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VEquipo.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_VEQUIPO_H)
#define _VEQUIPO_H
#include "VGeneral.h"

class VEquipo : public VGeneral {
public:
	VEquipo();
	void ImprimrirEquipo(float pv,float mi, float mf);
};

#endif  //_VEQUIPO_H
