//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VGeneral.cpp
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#include "VGeneral.h"

VGeneral::VGeneral() {}

void VGeneral::Pausa() {
system("pause");
}

void VGeneral::Limpiar() {
system("cls");
}

int VGeneral::SeleccionarRespuesta(string msj) {
	int res;
	cout<<msj<<endl;
	cin>>res;
	return res;
}

void VGeneral::ImprimirEncabezado(string msj1, string msj2) {
	cout<<msj1<<endl;
	cout<<msj2<<endl<<endl;
}

long VGeneral::LeerLong(string msj) {
	long c;
	cout<<msj<<endl;
	cin>>c;
	return c;
}

string VGeneral::LeerString(string msj) {
	string n;
	cout<<msj<<endl;
	cin.sync();
	getline(cin,n);
	return n;
}

float VGeneral::LeerFloat(string msj) {
	float num;
	cout<<msj<<endl;
	cin>>num;
	return num;

}
int VGeneral::LeerInt(string msj) {
	int n;
	cout <<msj<<endl;
	cin>>n;
	return n;
}
char VGeneral::LeerChar(string msj) {
	char n;
	cout <<msj<<endl;
	cin>>n;
	return n;
}

void VGeneral::ImprimirFloat(float num) {
cout<<setiosflags(ios::fixed)<<setprecision(2)<<num<<endl;
}

