//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : VGeneral.h
//  @ Date : 06/12/2011
//  @ Author : Pedro Gabriel Leal
//
//


#if !defined(_VGENERAL_H)
#define _VGENERAL_H
#include <string>
#include <iomanip>
#include <cstdlib>
#include <iostream>
using namespace std;

class VGeneral {
public:
	VGeneral();
	void Pausa();
	void Limpiar();
	int SeleccionarRespuesta(string msj);
	void ImprimirEncabezado(string msj1, string msj2);
	long LeerLong(string msj);
	string LeerString(string msj);
	float LeerFloat(string msj);
	int LeerInt(string msj);
	char LeerChar(string msj);
	void ImprimirFloat(float num);
};

#endif  //_VGENERAL_H
